version: '3.2'

services:
  danted:
    image: danted
    build: .
    restart: always
    network_mode: "bridge"
    ports:
      - '1080:1080'
    environment:
      - DANTE_HOST= #hostname or ip
      - DANTE_USER=
      - DANTE_PASSWORD=
